# Generated by Django 4.1.1 on 2022-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_document_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="final_copy",
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
