# Generated by Django 4.1.1 on 2022-09-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_document_signing_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="doc_title",
            field=models.CharField(default="sample", max_length=10),
        ),
    ]
